### ISSUE TITLE
Need a new Icon

### ISSUE THREAD

**Issue by richienyhus** [HaikuArchives/NightAndDay#1]
Maybe a sun and a moon????

**Comment by stephanie-fu** [comment]
![nightday_png](https://cloud.githubusercontent.com/assets/12781003/11916346/9ed39090-a698-11e5-990f-f9c7b06fa64d.png)

**Comment by waddlesplash** [comment]
Do you have that in HVIF format, @dash102?

**Comment by stephanie-fu** [comment]
It says "Unfortunately, we don't support that file type." Do I upload both files in a .zip file or something?

**Comment by stephanie-fu** [comment]
I think this should work
[NightDay.zip](https://github.com/HaikuArchives/NightAndDay/files/67690/NightDay.zip)

**Comment by waddlesplash** [comment]
@dash102 Did you claim the GCI task yet? I don't see your claim...
Anyway, looks good.

**Comment by stephanie-fu** [comment]
I submitted the task "Fix an open issue for NightAndDay (Haiku)"

**Comment by waddlesplash** [comment]
Thank you!
